#!/bin/bash
#
# this script will make a releaseable, non-platform specific package from the development 
# subversion dirs. After running this script, you should expect find a tarball and zip in:
#
#   build/bundle/discovery2-client/
#
# LEGAL NOTICE
# -------------
# 
# OSS Discovery is a tool that finds installed open source software.
#    Copyright (C) 2007 OpenLogic, Inc.
#  
# OSS Discovery is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3 as 
# published by the Free Software Foundation.  
#  
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License version 3 (discovery2-client/license/OSSDiscoveryLicense.txt) 
# for more details.
#  
# You should have received a copy of the GNU Affero General Public License along with this program.  
# If not, see http://www.gnu.org/licenses/
#
# You can learn more about OSSDiscovery, report bugs and get the latest versions at www.ossdiscovery.org.
# You can contact the OSS Discovery team at info@ossdiscovery.org.
# You can contact OpenLogic at info@openlogic.com.



DISCOVERSION=2
MINOR=alpha-3
DISTDIR=build/dist/discovery$DISCOVERSION-client
TARDIR=build/bundle/discovery$DISCOVERSION-client

# clean up old bits
rm -rf $DISTDIR/*
rm -rf $TARDIR/*

if [ ! -d build ]
then
    mkdir -p $DISTDIR
    mkdir -p $TARDIR
fi

# take top-level launch scripts
cp discovery* $DISTDIR

cp -r lib $DISTDIR
cp -r bin $DISTDIR
cp -r license $DISTDIR
mkdir $DISTDIR/log

pushd . 
cd $DISTDIR
echo It is normal for \'No such file or directory\' to be issued here. Ignore them
find . -name ".svn" -exec rm -rf {} \;
popd

cd build/dist
pwd
tar cvfz ../../$TARDIR/discovery$DISCOVERSION-client.$MINOR.tar.gz discovery$DISCOVERSION-client
zip -r ../../$TARDIR/discovery$DISCOVERSION-client.$MINOR.zip discovery$DISCOVERSION-client

echo You can find your zip and tar archives in $TARDIR/discovery$DISCOVERSION-client.$MINOR.tar.gz
